// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActiveSessionMessageDelivery } from "./ActiveSessionMessageDelivery";

export type ActiveSessionSendParams = { targetThreadId: string, message: string, senderThreadId?: string | null, senderLabel?: string | null, delivery?: ActiveSessionMessageDelivery | null, };
