// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { ActiveSessionCapability } from "./ActiveSessionCapability";
import type { ActiveSessionPeerKind } from "./ActiveSessionPeerKind";
import type { AuthProfileKind } from "./AuthProfileKind";

export type ActiveSessionPeer = {
/**
 * Active peer routing key returned by activeSession/list. For local
 * Codewith sessions this matches thread_id; bridge peers may use a
 * transport-scoped id.
 */
peerId: string, kind: ActiveSessionPeerKind,
/**
 * Codewith thread that owns the active peer registration.
 */
threadId: string,
/**
 * Live session instance id for the loaded thread. This is not a durable
 * mailbox or remote machine id.
 */
sessionId: string, cwd: AbsolutePathBuf, displayName: string | null, agentPath: string | null,
/**
 * Auth profile selected for model requests in this active peer, if known.
 */
authProfile: string | null,
/**
 * Whether `authProfile` is the default root profile or a named profile.
 */
authProfileKind: AuthProfileKind, capabilities: Array<ActiveSessionCapability>, lastSeenAt: bigint, };
