// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActiveSessionSendStatus } from "./ActiveSessionSendStatus";

export type ActiveSessionSendResponse = { status: ActiveSessionSendStatus, messageId: string, targetThreadId: string, senderThreadId: string | null, reason: string | null, };
