// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActiveSessionMessageDelivery } from "./ActiveSessionMessageDelivery";

export type ActiveSessionSendParams = {
/**
 * Legacy local Codewith-thread target. target_peer_id is preferred for
 * peers returned by activeSession/list.
 */
targetThreadId?: string | null,
/**
 * Active peer routing key from activeSession/list.
 */
targetPeerId?: string | null, message: string,
/**
 * Claimed sender thread for attribution only. activeSession/send does not
 * treat this as authentication or authorization.
 */
senderThreadId?: string | null,
/**
 * Claimed sender label for attribution only.
 */
senderLabel?: string | null, delivery?: ActiveSessionMessageDelivery | null, };
