// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { ActiveSessionCapability } from "./ActiveSessionCapability";
import type { ActiveSessionPeerKind } from "./ActiveSessionPeerKind";

export type ActiveSessionPeer = { peerId: string, kind: ActiveSessionPeerKind, threadId: string, sessionId: string, cwd: AbsolutePathBuf, displayName: string | null, agentPath: string | null, capabilities: Array<ActiveSessionCapability>, lastSeenAt: bigint, };
