// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActiveSessionSendStatus } from "./ActiveSessionSendStatus";

export type ActiveSessionSendResponse = { status: ActiveSessionSendStatus,
/**
 * App-server-generated id for this active delivery attempt. It is not a
 * durable mailbox id or read receipt.
 */
messageId: string, targetPeerId: string, targetThreadId: string | null,
/**
 * Echoes the claimed sender_thread_id when present and valid.
 */
senderThreadId: string | null, reason: string | null, };
