// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdditionalContextKind } from "./AdditionalContextKind";
import type { AdditionalContextSource } from "./AdditionalContextSource";

export type AdditionalContextEntry = { value: string, kind: AdditionalContextKind,
/**
 * Optional provenance for client-supplied context from a local app store.
 *
 * This metadata is for clients and auditability. It does not change
 * model-visible content or trust: `kind` remains the authority for whether
 * `value` is injected as untrusted user context or application context.
 */
source: AdditionalContextSource | null, };
