// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdditionalContextSource = {
/**
 * Stable source namespace, for example `open-projects`, `open-todos`,
 * `open-conversations`, or `open-mementos`.
 */
namespace: string,
/**
 * Stable record id inside the source namespace.
 */
id: string,
/**
 * Optional source record kind, for example `project`, `task`,
 * `conversation`, or `memento`.
 */
recordType: string | null,
/**
 * Optional user-facing label for rendering/editing the context source.
 */
label: string | null, };
