// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { AgentDesiredState } from "./AgentDesiredState";
import type { AgentRetentionState } from "./AgentRetentionState";
import type { AgentRunStatus } from "./AgentRunStatus";

export type AgentRun = { agentId: string, idempotencyKey: string | null, requestId: string | null, source: string, promptSnapshotRef: string, inputSnapshotRef: string | null, threadId: string | null, threadStoreKind: string, threadStoreId: string | null, rolloutPath: string | null, parentThreadId: string | null, parentAgentRunId: string | null, spawnLinkage: JsonValue | null, worktreeLeaseId: string | null, authProfileRef: string | null, desiredState: AgentDesiredState, status: AgentRunStatus, statusReason: string | null, configFingerprint: string | null, versionFingerprint: string | null, retentionState: AgentRetentionState, archiveAfter: number | null, deleteAfter: number | null, archivedAt: number | null, deletedAt: number | null, supervisorId: string | null, generation: number, pid: number | null, pgid: number | null, jobId: string | null, heartbeatAt: number | null, crashReason: string | null, exitCode: number | null, exitSignal: number | null, lastEventSeq: number, lastSnapshotSeq: number, createdAt: number, updatedAt: number, startedAt: number | null, completedAt: number | null, };
