// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type AgentExecutionContextParams = { workspaceRoots?: Array<string> | null, permissionProfile?: JsonValue | null, sandboxPolicy?: JsonValue | null, networkPolicy?: JsonValue | null, model?: string | null, provider?: string | null, serviceTier?: string | null, mcpToolAllowlist?: Array<string> | null, envSnapshotPolicy?: string | null, shellSnapshot?: JsonValue | null, configSourceHashes?: JsonValue | null, maxRuntimeSeconds?: number | null, maxTokens?: number | null, recoveryPolicy?: string | null, };
