// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { AgentDesiredState } from "./AgentDesiredState";
import type { AgentRunStatus } from "./AgentRunStatus";

export type AgentStatusSnapshot = { agentId: string, seq: number, status: AgentRunStatus, desiredState: AgentDesiredState, summary: string | null, pendingInteractionCount: number, lastEventSeq: number, payload: JsonValue, updatedAt: number, };
