// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type AgentModelAttestation = { agentId: string, idempotencyKeySha256: string | null, configFingerprint: string | null, requestedModel: string | null, requestedConfiguration: JsonValue, appliedModel: string | null, appliedConfiguration: JsonValue, boundRuntimeModel: string | null, };
