// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { AgentPendingInteractionKind } from "./AgentPendingInteractionKind";
import type { AgentPendingInteractionStatus } from "./AgentPendingInteractionStatus";

export type AgentPendingInteraction = { interactionId: string, agentId: string, workerRequestId: string | null, kind: AgentPendingInteractionKind, status: AgentPendingInteractionStatus, requestPayload: JsonValue, responsePayload: JsonValue | null, noClientPolicy: string, timeoutAt: number | null, createdAt: number, deliveredAt: number | null, respondedAt: number | null, updatedAt: number, };
