// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMode } from "../AuthMode";
import type { AuthProfileSubscriptionProvider } from "./AuthProfileSubscriptionProvider";

export type AuthProfileSummary = { name: string, subscriptionProvider: AuthProfileSubscriptionProvider, authMode: AuthMode | null, email: string | null, accountId: string | null, plan: string | null, active: boolean, };
