// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollabAgentStatus } from "./CollabAgentStatus";

export type CollabAgentState = { status: CollabAgentStatus, message: string | null,
/**
 * Canonical, human-readable agent path for this agent (for example
 * `/root/verify_bcr_statement_emails`), when the emitting event knows it.
 *
 * Spawn notifications populate this so a client can render the freshly spawned child's
 * hierarchical tree path (`root/<task>`) in the "Spawned" row immediately, instead of falling
 * back to a raw thread-id prefix while it waits for the child's own `ThreadStarted` to land.
 */
agentPath?: string, };
