// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConsumeAccountRateLimitResetCreditParams = {
/**
 * Identifies one logical reset attempt. A UUID is recommended; reuse the same value when
 * retrying that attempt.
 */
idempotencyKey: string,
/**
 * Opaque reset-credit identifier to redeem. When omitted, the backend selects the next
 * available credit.
 */
creditId?: string | null,
/**
 * Auth profile used for this reset. `null` selects the default root auth;
 * omission leaves the app-server's selected auth profile unchanged.
 */
authProfile?: string | null,
/**
 * Required opaque account fingerprint from the read that selected this reset credit.
 */
expectedAccountIdentityFingerprint: string, };
