// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetAccountRateLimitsParams = {
/**
 * Auth profile used for this read. `null` selects the default root auth;
 * omission leaves the app-server's selected auth profile unchanged.
 */
authProfile?: string | null, };
