// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateLimitResetCreditsSummary } from "./RateLimitResetCreditsSummary";
import type { RateLimitSnapshot } from "./RateLimitSnapshot";

export type GetAccountRateLimitsResponse = {
/**
 * Process-scoped opaque fingerprint of the authenticated account.
 *
 * `null` means the current ChatGPT credentials do not expose an account identifier. Clients
 * must not display or log this value and must treat its representation as opaque.
 */
accountIdentityFingerprint: string | null,
/**
 * Backward-compatible single-bucket view; mirrors the historical payload.
 */
rateLimits: RateLimitSnapshot,
/**
 * Multi-bucket view keyed by metered `limit_id` (for example, `codex`).
 */
rateLimitsByLimitId: { [key in string]?: RateLimitSnapshot } | null, rateLimitResetCredits: RateLimitResetCreditsSummary | null, };
