// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActiveSessionCapability } from "./ActiveSessionCapability";
import type { ActiveSessionPeerKind } from "./ActiveSessionPeerKind";

export type LocalSessionPeer = { peerId: string, kind: ActiveSessionPeerKind, capabilities: Array<ActiveSessionCapability>, lastSeenAt: number, };
