// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { AuthProfileKind } from "./AuthProfileKind";
import type { LocalSessionGitInfo } from "./LocalSessionGitInfo";
import type { LocalSessionPeer } from "./LocalSessionPeer";
import type { LocalSessionRedaction } from "./LocalSessionRedaction";
import type { LocalSessionStatus } from "./LocalSessionStatus";
import type { SessionSource } from "./SessionSource";
import type { ThreadActiveFlag } from "./ThreadActiveFlag";
import type { ThreadSource } from "./ThreadSource";

export type LocalSession = {
/**
 * Durable Codewith thread id for the session record.
 */
threadId: string,
/**
 * Live session instance id when known. Persisted-only records return null
 * because a durable thread id is not the same as a runtime session id.
 */
runtimeSessionId: string | null,
/**
 * Live active-session routing metadata when this record can receive
 * in-memory activeSession/send traffic.
 */
peer: LocalSessionPeer | null, status: LocalSessionStatus,
/**
 * Active-status flags from the thread runtime. Empty for non-active
 * sessions.
 */
activeFlags: Array<ThreadActiveFlag>, cwd: AbsolutePathBuf, displayName: string | null, agentPath: string | null, modelProvider: string, model: string | null,
/**
 * Auth profile selected for model requests in this session, if known.
 */
authProfile: string | null,
/**
 * Whether `authProfile` is unknown, the default root profile, or a named profile.
 */
authProfileKind: AuthProfileKind,
/**
 * Redacted account label for the selected auth profile, when available.
 */
accountLabel: string | null, source: SessionSource, threadSource: ThreadSource | null, createdAt: number, updatedAt: number, path: string | null, gitInfo: LocalSessionGitInfo | null, redactions: Array<LocalSessionRedaction>, };
