// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MissionControlCapabilities } from "./MissionControlCapabilities";
import type { MissionControlSession } from "./MissionControlSession";
import type { ThreadPendingInteraction } from "./ThreadPendingInteraction";

export type MissionControlOverviewResponse = { sessions: Array<MissionControlSession>, pendingInteractions: Array<ThreadPendingInteraction>, nextSessionCursor: string | null, nextPendingInteractionCursor: string | null, capabilities: MissionControlCapabilities, };
