// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalSession } from "./LocalSession";
import type { ThreadGoal } from "./ThreadGoal";
import type { ThreadGoalPlan } from "./ThreadGoalPlan";

export type MissionControlSession = { session: LocalSession, goal: ThreadGoal | null, goalPlans: Array<ThreadGoalPlan>, };
