// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadPendingInteractionResponsePayload } from "./ThreadPendingInteractionResponsePayload";
import type { ThreadPendingInteractionTerminalStatus } from "./ThreadPendingInteractionTerminalStatus";

export type MissionControlRespondInteractionParams = { interactionId: string, threadId?: string | null, terminalStatus: ThreadPendingInteractionTerminalStatus, response: ThreadPendingInteractionResponsePayload, dryRun?: boolean, };
