// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MissionControlEnqueueInstructionParams = { targetThreadId: string, message: string, senderThreadId?: string | null, senderLabel?: string | null, idempotencyKey?: string | null, priority?: bigint | null, maxAttempts?: number | null, expiresAt?: number | null, resume?: boolean, dryRun?: boolean, };
