// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MissionControlCapabilities = { localSessions: boolean, durableMailbox: boolean, pendingInteractions: boolean, goals: boolean, remoteDispatch: boolean, workflowMutation: boolean, shellExecution: boolean, filesystemMutation: boolean, };
