// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MissionControlDeliveryPolicy } from "./MissionControlDeliveryPolicy";
import type { ThreadMailboxMessageSummary } from "./ThreadMailboxMessageSummary";

export type MissionControlEnqueueInstructionResponse = { dryRun: boolean, deliveryPolicy: MissionControlDeliveryPolicy, preview: string, message: ThreadMailboxMessageSummary | null, created: boolean | null, };
