// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalSessionStatus } from "./LocalSessionStatus";
import type { SortDirection } from "./SortDirection";
import type { ThreadPendingInteractionStatus } from "./ThreadPendingInteractionStatus";
import type { ThreadSortKey } from "./ThreadSortKey";

export type MissionControlOverviewParams = { cursor?: string | null, limit?: number | null, sortKey?: ThreadSortKey | null, sortDirection?: SortDirection | null, cwd?: string | Array<string> | null, sessionStatuses?: Array<LocalSessionStatus> | null, searchTerm?: string | null, pendingInteractionCursor?: string | null, pendingInteractionLimit?: number | null, pendingInteractionStatuses?: Array<ThreadPendingInteractionStatus> | null, includeGoalPlans?: boolean, useStateDbOnly?: boolean, };
