// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelGatewayKind } from "./ModelGatewayKind";
import type { ModelProviderAuthKind } from "./ModelProviderAuthKind";

export type ModelProviderSummary = { id: string, name: string, modelGateway: string, modelGatewayName: string, modelGatewayKind: ModelGatewayKind, authKind: ModelProviderAuthKind, requiresOpenaiAuth: boolean, isCurrent: boolean, };
