// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelListParams = {
/**
 * Opaque pagination cursor returned by a previous call.
 */
cursor?: string | null,
/**
 * Optional page size; defaults to a reasonable server-side value.
 */
limit?: number | null,
/**
 * When true, include models that are hidden from the default picker list.
 */
includeHidden?: boolean | null,
/**
 * Provider id whose models should be listed. Omission uses the active provider.
 */
modelProvider?: string | null,
/**
 * Gateway id to scope model browsing. Omission preserves active/provider behavior.
 */
modelGateway?: string | null,
/**
 * Aggregator upstream provider id, such as the prefix in OpenRouter model slugs.
 */
upstreamProvider?: string | null, };
