// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelProviderListParams = {
/**
 * Gateway id to scope provider browsing. Omission preserves the provider-only catalog.
 */
modelGateway?: string | null, };
