// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelGatewayKind } from "./ModelGatewayKind";

export type ModelGatewaySummary = { id: string, name: string, kind: ModelGatewayKind, isCurrent: boolean, };
