// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Privacy-safe classification for failures returned by a model provider.
 */
export type ProviderFailureKind = "unauthorized" | "rateLimit" | "server" | "stream" | "transport" | "unknown";
