// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PullRequest } from "./PullRequest";
import type { PullRequestQueryState } from "./PullRequestQueryState";

export type PullRequestListResponse = { queryState: PullRequestQueryState, data: Array<PullRequest>, nextCursor: string | null, message: string | null, };
