// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * In-band outcome of a pull-request query.
 *
 * Pull-request data is sourced asynchronously and may be unavailable (for
 * example when no GitHub remote is configured or the backing processor has not
 * been implemented yet). Rather than surfacing these outcomes as JSON-RPC
 * errors, every pull-request response carries a [`PullRequestQueryState`] so
 * clients can render empty/loading/degraded states in-band.
 */
export type PullRequestQueryState = "ready" | "loading" | "unavailable";
