// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PullRequestOverview } from "./PullRequestOverview";
import type { PullRequestQueryState } from "./PullRequestQueryState";

export type PullRequestOverviewResponse = { queryState: PullRequestQueryState, overview: PullRequestOverview | null, message: string | null, };
