// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PullRequest } from "./PullRequest";

/**
 * Aggregate view of the pull requests relevant to the current repository.
 */
export type PullRequestOverview = { totalOpen: number, totalDraft: number, authoredByViewer: number, awaitingViewerReview: number, recentlyUpdated: Array<PullRequest>, };
