// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PullRequestReviewDecision } from "./PullRequestReviewDecision";
import type { PullRequestState } from "./PullRequestState";

export type PullRequest = { id: string, number: number, title: string, state: PullRequestState, isDraft: boolean, author: string | null, url: string | null, repository: string | null, headRef: string | null, baseRef: string | null, reviewDecision: PullRequestReviewDecision | null, createdAt: number, updatedAt: number, };
