// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateLimitResetCreditStatus } from "./RateLimitResetCreditStatus";
import type { RateLimitResetType } from "./RateLimitResetType";

export type RateLimitResetCredit = { id: string, resetType: RateLimitResetType, status: RateLimitResetCreditStatus, grantedAt: number, expiresAt: number | null, title: string | null, description: string | null, };
