// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadScheduleIntervalUnit } from "./ThreadScheduleIntervalUnit";

export type ThreadScheduleSpec = { "type": "once" } | { "type": "dynamic" } | { "type": "interval", amount: number, unit: ThreadScheduleIntervalUnit, } | { "type": "cron", expression: string, };
