// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadWorkflowRunStatus = "pending" | "running" | "waiting" | "blocked" | "paused" | "cancelRequested" | "cancelled" | "failed" | "completed" | "other";
