// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadScheduleRun } from "./ThreadScheduleRun";

export type ThreadScheduleRunUpdatedNotification = { threadId: string, run: ThreadScheduleRun, };
