// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a surfaced external-agent permission request was ultimately resolved.
 *
 * Included in [`ThreadExternalAgentEvent::PermissionResolved`] so clients can
 * keep an audit trail that distinguishes an explicit client decision from a
 * server-applied default-deny.
 */
export type ThreadExternalAgentPermissionResolution = "client" | "timedOut" | "defaultDenied" | "superseded";
