// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadMonitorRouting } from "./ThreadMonitorRouting";
import type { ThreadMonitorStatus } from "./ThreadMonitorStatus";

export type ThreadMonitor = { threadId: string, monitorId: string, name: string, prompt: string, command: string, cwd: string | null, routing: ThreadMonitorRouting, outputFile: string | null, status: ThreadMonitorStatus, generation: number, processId: number | null, lastEventAt: number | null, lastError: string | null, createdAt: number, updatedAt: number, };
