// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadGoal } from "./ThreadGoal";
import type { ThreadGoalPlan } from "./ThreadGoalPlan";
import type { ThreadGoalPlanNode } from "./ThreadGoalPlanNode";

export type ThreadGoalPlanAddGoalResponse = { goal: ThreadGoal | null, plan: ThreadGoalPlan, addedNode: ThreadGoalPlanNode, createdPlan: boolean, };
