// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Execution surface an external-agent run should target.
 *
 * `acp` runs the runtime as a local ACP stdio subprocess, `sdk-local` runs the
 * runtime's local SDK/CLI stream on this machine, and `cloud` delegates the run
 * to the runtime's hosted (cloud) agent. The surface a run may use is bounded by
 * the runtime's advertised descriptor (see `ExternalAgentRuntimeDescriptor`).
 */
export type ThreadExternalAgentExecutionSurface = "acp" | "sdk-local" | "cloud";
