// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { CommandExecutionApprovalDecision } from "./CommandExecutionApprovalDecision";
import type { DynamicToolCallOutputContentItem } from "./DynamicToolCallOutputContentItem";
import type { FileChangeApprovalDecision } from "./FileChangeApprovalDecision";
import type { GrantedPermissionProfile } from "./GrantedPermissionProfile";
import type { McpServerElicitationAction } from "./McpServerElicitationAction";
import type { PermissionGrantScope } from "./PermissionGrantScope";
import type { ToolRequestUserInputAnswer } from "./ToolRequestUserInputAnswer";

export type ThreadPendingInteractionResponsePayload = { "type": "commandApproval", decision: CommandExecutionApprovalDecision, } | { "type": "fileChangeApproval", decision: FileChangeApprovalDecision, } | { "type": "requestUserInput", answers: { [key in string]?: ToolRequestUserInputAnswer }, } | { "type": "mcpElicitation", action: McpServerElicitationAction, content: JsonValue | null, meta: JsonValue | null, } | { "type": "permissionsApproval", permissions: GrantedPermissionProfile, scope: PermissionGrantScope, strictAutoReview: boolean | null, } | { "type": "dynamicTool", contentItems: Array<DynamicToolCallOutputContentItem>, success: boolean, } | { "type": "terminal", reason: string, };
