// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadMonitor } from "./ThreadMonitor";
import type { ThreadMonitorEvent } from "./ThreadMonitorEvent";

export type ThreadMonitorEventNotification = { threadId: string, monitor: ThreadMonitor, event: ThreadMonitorEvent, };
