// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadWorkflowRun } from "./ThreadWorkflowRun";
import type { ThreadWorkflowRunEvent } from "./ThreadWorkflowRunEvent";
import type { ThreadWorkflowRunStep } from "./ThreadWorkflowRunStep";
import type { ThreadWorkflowRunStepVerifier } from "./ThreadWorkflowRunStepVerifier";

export type ThreadWorkflowRunSnapshot = { run: ThreadWorkflowRun, steps: Array<ThreadWorkflowRunStep>, verifiers: Array<ThreadWorkflowRunStepVerifier>, events: Array<ThreadWorkflowRunEvent>, };
