// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadScheduleStats = { totalRuns: number, leasedRuns: number, runningRuns: number, completedRuns: number, failedRuns: number, lastStartedAt: number | null, lastCompletedAt: number | null, lastError: string | null, };
