// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadScheduleSpec } from "./ThreadScheduleSpec";
import type { ThreadScheduleStatus } from "./ThreadScheduleStatus";

export type ThreadScheduleUpdateParams = { threadId: string, scheduleId: string, prompt?: string | null, schedule?: ThreadScheduleSpec | null, timezone?: string | null, status?: ThreadScheduleStatus | null, nextRunAt?: number | null, expiresAt?: number | null, };
