// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadWorkflowRun } from "./ThreadWorkflowRun";

/**
 * Server -> client notification emitted whenever a workflow run's status or
 * progress counters change (start, pause, resume, cancel, and future runtime
 * transitions). Carries the run summary so subscribers can track progress
 * without re-fetching the full snapshot.
 */
export type ThreadWorkflowRunUpdatedNotification = { threadId: string, run: ThreadWorkflowRun, };
