// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { ThreadMailboxMessageStatus } from "./ThreadMailboxMessageStatus";
import type { ThreadMailboxReceiptKind } from "./ThreadMailboxReceiptKind";

export type ThreadMailboxReceipt = { receiptId: string, messageId: string, attemptId: string | null, threadId: string, kind: ThreadMailboxReceiptKind, statusAfter: ThreadMailboxMessageStatus, payload: JsonValue | null, createdAt: number, };
