// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadWorkflowRunEvent = { seq: number, eventType: string, actorKind: string, actorId: string | null, stepRunId: string | null, verifierRunId: string | null, visibility: string, createdAt: number, };
