// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadWorkflowRunStepStatus } from "./ThreadWorkflowRunStepStatus";

export type ThreadWorkflowRunStep = { stepRunId: string, stepId: string, sequence: number, title: string, agentId: string, status: ThreadWorkflowRunStepStatus, statusReason: string | null, reasonCode: string | null, dependsOn: Array<string>, backgroundAgentRunId: string | null, createdAt: number, updatedAt: number, startedAt: number | null, completedAt: number | null, };
