// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSchedulePromptSource } from "./ThreadSchedulePromptSource";
import type { ThreadScheduleSpec } from "./ThreadScheduleSpec";
import type { ThreadScheduleStatus } from "./ThreadScheduleStatus";

export type ThreadSchedule = { threadId: string, scheduleId: string, parentScheduleId: string | null, nestingDepth: number, prompt: string, promptSource: ThreadSchedulePromptSource, schedule: ThreadScheduleSpec, timezone: string, status: ThreadScheduleStatus, nextRunAt: number | null, lastRunAt: number | null, expiresAt: number | null, failureCount: number, leaseExpiresAt: number | null, createdAt: number, updatedAt: number, };
