// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadMailboxMessageKind } from "./ThreadMailboxMessageKind";
import type { ThreadMailboxMessageStatus } from "./ThreadMailboxMessageStatus";
import type { ThreadMailboxRedaction } from "./ThreadMailboxRedaction";

export type ThreadMailboxMessageSummary = { messageId: string, targetThreadId: string, senderThreadId: string | null, senderLabel: string | null, kind: ThreadMailboxMessageKind, status: ThreadMailboxMessageStatus, payloadSha256: string, payloadPreview: string, redactions: Array<ThreadMailboxRedaction>, priority: bigint, attemptCount: bigint, maxAttempts: bigint, nextAttemptAt: number, leaseExpiresAt: number | null, lastError: string | null, expiresAt: number | null, acknowledgedAt: number | null, terminalAt: number | null, createdAt: number, updatedAt: number, };
