// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadMonitorRouting } from "./ThreadMonitorRouting";

export type ThreadMonitorCreateParams = { threadId: string, name: string, prompt: string, command: string,
/**
 * Optional working directory relative to the thread cwd. Parent directory
 * traversal and absolute paths are rejected.
 */
cwd?: string | null, routing?: ThreadMonitorRouting | null,
/**
 * Optional output file relative to the monitor cwd. Parent directory
 * traversal, absolute paths, and symlink targets are rejected.
 */
outputFile?: string | null, };
