// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadWorkflowApprovalGate } from "./ThreadWorkflowApprovalGate";

/**
 * Workflow-scoped approval-review context for a run.
 *
 * Lets `/workflows` decide whether to enable its approval affordance and, if
 * so, surface the pending gates. The manager should keep approval rows
 * disabled unless `available` is true and keep the approval action disabled
 * unless `actionable` is true.
 */
export type ThreadWorkflowApprovalReview = {
/**
 * The run declares run-level approval gates (`approvals.required_before`).
 */
hasApprovalConfig: boolean,
/**
 * Any workflow-scoped approval data is available (config or a pending gate).
 */
available: boolean,
/**
 * There is a pending approval to act on.
 */
actionable: boolean, pendingCount: number,
/**
 * Compact, sanitized list of steps awaiting an approval review.
 */
pendingGates: Array<ThreadWorkflowApprovalGate>, };
