// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadMonitorEventStream } from "./ThreadMonitorEventStream";

export type ThreadMonitorEvent = { threadId: string, monitorId: string, eventId: string, stream: ThreadMonitorEventStream, text: string, createdAt: number, };
