// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadExternalAgentExecutionSurface } from "./ThreadExternalAgentExecutionSurface";

/**
 * A single discoverable model for an external-agent runtime.
 */
export type ThreadExternalAgentModel = { id: string, displayName: string, description?: string,
/**
 * Execution surfaces this model can run on.
 */
executionSurfaces: Array<ThreadExternalAgentExecutionSurface>, };
