// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadGoalPlanNodeStatus } from "./ThreadGoalPlanNodeStatus";

export type ThreadGoalPlanNode = { nodeId: string, planId: string, threadId: string, key: string, sequence: number, priority: number, objective: string, status: ThreadGoalPlanNodeStatus, tokenBudget: number | null, tokensUsed: number, timeUsedSeconds: number, projectedGoalId: string | null, dependsOn: Array<string>, createdAt: number, updatedAt: number, };
