// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadGoalPlanNodeInsertPosition } from "./ThreadGoalPlanNodeInsertPosition";

export type ThreadGoalPlanInsertNodeParams = { threadId: string, planId: string, position: ThreadGoalPlanNodeInsertPosition, referenceNodeId?: string | null, key: string, objective: string, title?: string | null, priority?: bigint | null, tokenBudget?: bigint | null, dependsOn?: Array<string> | null, };
