// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A workflow step currently gated behind a pending approval review.
 *
 * Only carries the author-defined step id and approval-gate label so a
 * manager can display or link to the approval-review flow. Never contains a
 * raw approvals payload, prompt, or secret.
 */
export type ThreadWorkflowApprovalGate = { stepId: string, gate: string, };
