// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadScheduleRunStatus } from "./ThreadScheduleRunStatus";

export type ThreadScheduleRun = { threadId: string, scheduleId: string, runId: string, status: ThreadScheduleRunStatus, leaseId: string, turnId: string | null, error: string | null, scheduledForAt: number | null, startedAt: number, completedAt: number | null, };
