// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadQueuedMessage = { messageId: string, threadId: string,
/**
 * 1-based position in the pending agent-message mailbox.
 */
position: number, author: string, recipient: string, text: string, triggerTurn: boolean, };
