// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadQueuedMessage } from "./ThreadQueuedMessage";
import type { ThreadQueuedMessageStats } from "./ThreadQueuedMessageStats";

export type ThreadQueuedMessageListResponse = { data: Array<ThreadQueuedMessage>, nextCursor: string | null, stats: ThreadQueuedMessageStats, };
