// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadContinueParams = {
/**
 * Loaded destination thread that will receive the generated continuation recap.
 */
destinationThreadId: string,
/**
 * Persisted source thread whose effective history should be summarized.
 */
sourceThreadId: string, };
