// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSchedule } from "./ThreadSchedule";

export type ThreadScheduleUpdatedNotification = { threadId: string, schedule: ThreadSchedule, };
