// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { ThreadPendingInteractionKind } from "./ThreadPendingInteractionKind";
import type { ThreadPendingInteractionSourceKind } from "./ThreadPendingInteractionSourceKind";
import type { ThreadPendingInteractionStatus } from "./ThreadPendingInteractionStatus";

export type ThreadPendingInteraction = { interactionId: string, threadId: string, sourceKind: ThreadPendingInteractionSourceKind, sourceId: string | null, turnId: string | null, workerRequestId: string | null, kind: ThreadPendingInteractionKind, status: ThreadPendingInteractionStatus, requestPayload: JsonValue, requestPayloadSha256: string, requestPayloadPreview: string, requestRedactions: Array<string>, responsePayload: JsonValue | null, responsePayloadSha256: string | null, responsePayloadPreview: string | null, responseRedactions: Array<string>, noClientPolicy: string, timeoutAt: number | null, createdAt: number, deliveredAt: number | null, respondedAt: number | null, terminalAt: number | null, updatedAt: number, };
