// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadWorkflowRunStatus } from "./ThreadWorkflowRunStatus";

export type ThreadWorkflowRun = { threadId: string | null, runId: string, workflowRecordId: string, specWorkflowId: string, schemaVersion: string, sourceYamlSha256: string, status: ThreadWorkflowRunStatus, statusReason: string | null, reasonCode: string | null, generation: number, pendingStepCount: number, readyStepCount: number, activeStepCount: number, waitingVerifierStepCount: number, blockedStepCount: number, failedStepCount: number, succeededStepCount: number, skippedStepCount: number, verifierCount: number, eventCount: number, createdAt: number, updatedAt: number, startedAt: number, completedAt: number, };
