// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Durable artifact surfaced by a cloud external-agent run.
 */
export type ThreadExternalAgentCloudArtifact = { label: string, uri?: string, mimeType?: string, };
