// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadMonitorRouting } from "./ThreadMonitorRouting";

export type ThreadMonitorCreateParams = { threadId: string, name: string, prompt: string, command: string, cwd?: string | null, routing?: ThreadMonitorRouting | null, outputFile?: string | null, };
