// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSchedulePromptSource } from "./ThreadSchedulePromptSource";
import type { ThreadScheduleSpec } from "./ThreadScheduleSpec";

export type ThreadScheduleCreateParams = { threadId: string, parentScheduleId?: string | null, prompt: string, promptSource?: ThreadSchedulePromptSource | null, schedule: ThreadScheduleSpec, timezone?: string | null, nextRunAt?: bigint | null, expiresAt?: bigint | null, };
