// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadWorkflowRunStepVerifierStatus } from "./ThreadWorkflowRunStepVerifierStatus";

export type ThreadWorkflowRunStepVerifier = { verifierRunId: string, stepId: string, verifierId: string, verifierType: string, status: ThreadWorkflowRunStepVerifierStatus, statusReason: string | null, reasonCode: string | null, attemptCount: number, maxAttempts: number, createdAt: number, updatedAt: number, completedAt: number, };
