// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadGoalPlanAutoExecute } from "./ThreadGoalPlanAutoExecute";
import type { ThreadGoalPlanNode } from "./ThreadGoalPlanNode";
import type { ThreadGoalPlanStatus } from "./ThreadGoalPlanStatus";

export type ThreadGoalPlan = { planId: string, threadId: string, status: ThreadGoalPlanStatus, autoExecute: ThreadGoalPlanAutoExecute, maxTokens: number | null, createdAt: number, updatedAt: number, nodes: Array<ThreadGoalPlanNode>, };
