// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadGoalPlanNodeTitleUpdate } from "./ThreadGoalPlanNodeTitleUpdate";
import type { ThreadGoalPlanNodeTokenBudgetUpdate } from "./ThreadGoalPlanNodeTokenBudgetUpdate";

export type ThreadGoalPlanUpdateNodeParams = { threadId: string, nodeId: string, key?: string | null, objective?: string | null, title?: ThreadGoalPlanNodeTitleUpdate | null, priority?: bigint | null, tokenBudget?: ThreadGoalPlanNodeTokenBudgetUpdate | null, dependsOn?: Array<string> | null, };
