// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { ThreadExternalAgentMode } from "./ThreadExternalAgentMode";
import type { ThreadExternalAgentPermissionRequest } from "./ThreadExternalAgentPermissionRequest";

export type ThreadExternalAgentEvent = { "type": "runStarted", runtime_id: string, mode: ThreadExternalAgentMode, task: string, } | { "type": "sessionResolved", external_session_id: string | null, } | { "type": "outputTextDelta", text: string, } | { "type": "reasoningDelta", text: string, } | { "type": "planUpdated", plan: string, } | { "type": "permissionRequested", request: ThreadExternalAgentPermissionRequest, } | { "type": "proposedAction", proposal: JsonValue, } | { "type": "status", message: string, } | { "type": "completed", summary: string | null, } | { "type": "failed", message: string, } | { "type": "cancelled", reason: string | null, };
