// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebhookEventStatus } from "./WebhookEventStatus";
import type { WebhookPayloadRedaction } from "./WebhookPayloadRedaction";

export type WebhookEventSummary = { eventId: string, sourceAppId: string, sourceAppName: string | null, subscriptionId: string | null, eventType: string, externalDeliveryId: string | null, idempotencyKey: string | null, targetThreadId: string | null, status: WebhookEventStatus, payloadSha256: string, payloadPreview: string, redactions: Array<WebhookPayloadRedaction>, receivedAt: number, updatedAt: number, };
