// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebhookEventSummary } from "./WebhookEventSummary";

export type WebhookEventListResponse = { data: Array<WebhookEventSummary>, nextCursor: string | null, };
