// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type WebhookEventIngestParams = { sourceAppId: string, sourceAppName?: string | null, subscriptionId?: string | null, eventType: string, externalDeliveryId?: string | null, idempotencyKey?: string | null, targetThreadId?: string | null, payloadJson: JsonValue, };
