// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebhookEventStatus } from "./WebhookEventStatus";

export type WebhookEventListParams = { sourceAppId?: string | null, targetThreadId?: string | null, statuses?: Array<WebhookEventStatus> | null, cursor?: string | null, limit?: number | null, };
