// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorktreeCleanupPolicy } from "./WorktreeCleanupPolicy";

export type WorktreeCreateParams = { baseRepoPath?: string | null, name?: string | null, branch?: string | null, startPoint?: string | null, cleanupPolicy?: WorktreeCleanupPolicy | null, threadId?: string | null, };
