// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorktreeCleanupPolicy } from "./WorktreeCleanupPolicy";
import type { WorktreeSessionMode } from "./WorktreeSessionMode";

export type WorktreePolicy = { enabled: boolean, root: string | null, cleanupDefault: WorktreeCleanupPolicy, mainSessions: WorktreeSessionMode, subSessions: WorktreeSessionMode, currentBaseRepoPath: string | null, };
