// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorktreeMergeCandidateStatus } from "./WorktreeMergeCandidateStatus";

export type WorktreeMergeCandidate = { candidateId: string, worktreeId: string, targetRef: string, targetSha: string | null, baseSha: string, headSha: string, status: WorktreeMergeCandidateStatus, conflictSummary: string | null, createdAt: number, updatedAt: number, appliedAt: number | null, dismissedAt: number | null, };
