// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Worktree } from "./Worktree";
import type { WorktreePolicy } from "./WorktreePolicy";

export type WorktreeCreateResponse = { worktree: Worktree, policy: WorktreePolicy, };
