// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { AgentRun } from "./AgentRun";
import type { WorktreeCleanupPolicy } from "./WorktreeCleanupPolicy";
import type { WorktreeLifecycleStatus } from "./WorktreeLifecycleStatus";
import type { WorktreeMode } from "./WorktreeMode";
import type { WorktreeOwnerKind } from "./WorktreeOwnerKind";

export type Worktree = { worktreeId: string, agentId: string | null, identity: string | null, mode: WorktreeMode, lifecycleStatus: WorktreeLifecycleStatus, baseRepoPath: string, worktreePath: string, branch: string | null, baseSha: string | null, headSha: string | null, statusSnapshot: JsonValue, dirty: boolean, cleanupPolicy: WorktreeCleanupPolicy, cleanupAfter: number | null, forceDeleteRequested: boolean, ownerKind: WorktreeOwnerKind, ownerThreadId: string | null, ownerAgentRunId: string | null, createdAt: number, updatedAt: number, releasedAt: number | null, deletedAt: number | null, agent: AgentRun | null, };
