//! SQLite-backed state for rollout metadata.
//!
//! This crate is intentionally small and focused: it extracts rollout metadata
//! from JSONL rollouts and mirrors it into a local SQLite database. Backfill
//! orchestration and rollout scanning live in `codex-core`.

mod audit;
pub mod busy_retry;
mod extract;
pub mod log_db;
mod migrations;
mod model;
mod paths;
mod runtime;
mod telemetry;

pub use model::LogEntry;
pub use model::LogQuery;
pub use model::LogRow;
pub use model::Phase2JobClaimOutcome;
/// Preferred entrypoint: owns configuration and metrics.
pub use runtime::StateRuntime;
pub use runtime::StateRuntimeStartupLock;
pub use runtime::acquire_state_runtime_startup_lock;
pub use runtime::state_runtime_startup_lock_path;

pub use audit::ThreadStateAuditRow;
pub use audit::read_thread_state_audit_rows;
/// Low-level storage engine: useful for focused tests.
///
/// Most consumers should prefer [`StateRuntime`].
pub use extract::apply_rollout_item;
pub use extract::rollout_item_affects_thread_metadata;
pub use model::AgentJob;
pub use model::AgentJobCreateParams;
pub use model::AgentJobItem;
pub use model::AgentJobItemCreateParams;
pub use model::AgentJobItemStatus;
pub use model::AgentJobProgress;
pub use model::AgentJobStatus;
pub use model::Anchor;
pub use model::BACKGROUND_AGENT_EVENT_CURSOR_COMPACTED;
pub use model::BackfillState;
pub use model::BackfillStats;
pub use model::BackfillStatus;
pub use model::BackgroundAgentDesiredState;
pub use model::BackgroundAgentEvent;
pub use model::BackgroundAgentExecutionHandleParams;
pub use model::BackgroundAgentExecutionSnapshot;
pub use model::BackgroundAgentExecutionSnapshotParams;
pub use model::BackgroundAgentPendingInteraction;
pub use model::BackgroundAgentPendingInteractionCreateParams;
pub use model::BackgroundAgentPendingInteractionKind;
pub use model::BackgroundAgentPendingInteractionStatus;
pub use model::BackgroundAgentProcessHandleRecord;
pub use model::BackgroundAgentRetentionState;
pub use model::BackgroundAgentRun;
pub use model::BackgroundAgentRunCreateParams;
pub use model::BackgroundAgentRunStatus;
pub use model::BackgroundAgentStatusEventForSupervisorParams;
pub use model::BackgroundAgentStatusSnapshot;
pub use model::BackgroundAgentStatusSnapshotParams;
pub use model::BackgroundAgentThreadBindingParams;
pub use model::BackgroundAgentWorkspaceCleanup;
pub use model::BackgroundAgentWorkspaceMode;
pub use model::BackgroundAgentWorktreeLease;
pub use model::BackgroundAgentWorktreeLeaseCreateParams;
pub use model::DirectionalThreadSpawnEdgeStatus;
pub use model::ExtractionOutcome;
pub use model::MachineEndpoint;
pub use model::MachineEndpointTransport;
pub use model::MachineEnrollmentState;
pub use model::MachineHealthState;
pub use model::MachineRecord;
pub use model::MachineSourceKind;
pub use model::MachineTrustState;
pub use model::MailboxDeliveryAttempt;
pub use model::MailboxDeliveryAttemptStatus;
pub use model::MailboxMessage;
pub use model::MailboxMessageKind;
pub use model::MailboxMessageStatus;
pub use model::MailboxReceipt;
pub use model::MailboxReceiptKind;
pub use model::ManagedWorktree;
pub use model::ManagedWorktreeCleanupPolicy;
pub use model::ManagedWorktreeLifecycleStatus;
pub use model::ManagedWorktreeMergeCandidate;
pub use model::ManagedWorktreeMergeCandidateStatus;
pub use model::ManagedWorktreeMode;
pub use model::ManagedWorktreeOwnerKind;
pub use model::PendingInteraction;
pub use model::PendingInteractionCreateParams;
pub use model::PendingInteractionEvent;
pub use model::PendingInteractionEventKind;
pub use model::PendingInteractionKind;
pub use model::PendingInteractionRespondParams;
pub use model::PendingInteractionSourceKind;
pub use model::PendingInteractionStatus;
pub use model::PostGoalContextAction;
pub use model::SortDirection;
pub use model::SortKey;
pub use model::Stage1JobClaim;
pub use model::Stage1JobClaimOutcome;
pub use model::Stage1Output;
pub use model::Stage1StartupClaimParams;
pub use model::ThreadGoal;
pub use model::ThreadGoalPlan;
pub use model::ThreadGoalPlanAutoExecute;
pub use model::ThreadGoalPlanNode;
pub use model::ThreadGoalPlanNodeStatus;
pub use model::ThreadGoalPlanSnapshot;
pub use model::ThreadGoalPlanStatus;
pub use model::ThreadGoalPlanUsageSummary;
pub use model::ThreadGoalStatus;
pub use model::ThreadMetadata;
pub use model::ThreadMetadataBuilder;
pub use model::ThreadMonitor;
pub use model::ThreadMonitorEvent;
pub use model::ThreadMonitorEventStream;
pub use model::ThreadMonitorRouting;
pub use model::ThreadMonitorStatus;
pub use model::ThreadSchedule;
pub use model::ThreadScheduleInterval;
pub use model::ThreadScheduleIntervalUnit;
pub use model::ThreadSchedulePromptSource;
pub use model::ThreadScheduleRun;
pub use model::ThreadScheduleRunStatus;
pub use model::ThreadScheduleSpec;
pub use model::ThreadScheduleStats;
pub use model::ThreadScheduleStatus;
pub use model::ThreadsPage;
pub use model::WebhookEvent;
pub use model::WebhookEventStatus;
pub use model::WebhookPayloadRedaction;
pub use model::WorkflowRun;
pub use model::WorkflowRunEvent;
pub use model::WorkflowRunSnapshot;
pub use model::WorkflowRunStatus;
pub use model::WorkflowRunStep;
pub use model::WorkflowRunStepStatus;
pub use model::WorkflowRunStepVerifier;
pub use model::WorkflowRunStepVerifierStatus;
pub use model::WorkflowSpecRecord;
pub use model::WorkflowSpecStatus;
pub use runtime::DEFAULT_MACHINE_REGISTRY_LIST_LIMIT;
pub use runtime::DEFAULT_MAILBOX_MESSAGE_LIST_LIMIT;
pub use runtime::DEFAULT_MANAGED_WORKTREE_LIST_LIMIT;
pub use runtime::DEFAULT_PENDING_INTERACTION_LIST_LIMIT;
pub use runtime::DEFAULT_THREAD_GOAL_PLAN_LIST_LIMIT;
pub use runtime::DEFAULT_THREAD_WORKFLOW_LIST_LIMIT;
pub use runtime::DEFAULT_THREAD_WORKFLOW_RUN_LIST_LIMIT;
pub use runtime::DEFAULT_WEBHOOK_EVENT_LIST_LIMIT;
pub use runtime::GoalAccountingMode;
pub use runtime::GoalAccountingOutcome;
pub use runtime::GoalDeleteOutcome;
pub use runtime::GoalStore;
pub use runtime::GoalUpdate;
pub use runtime::LocalActiveSessionHeartbeatParams;
pub use runtime::LocalActiveSessionPruneOwnerParams;
pub use runtime::LocalActiveSessionRecord;
pub use runtime::LocalActiveSessionStore;
pub use runtime::MAX_MACHINE_REGISTRY_LIST_LIMIT;
pub use runtime::MAX_MAILBOX_MESSAGE_LIST_LIMIT;
pub use runtime::MAX_MANAGED_WORKTREE_LIST_LIMIT;
pub use runtime::MAX_PENDING_INTERACTION_LIST_LIMIT;
pub use runtime::MAX_THREAD_GOAL_PLAN_LIST_LIMIT;
pub use runtime::MAX_THREAD_SCHEDULE_NESTING_DEPTH;
pub use runtime::MAX_THREAD_WORKFLOW_LIST_LIMIT;
pub use runtime::MAX_THREAD_WORKFLOW_RUN_LIST_LIMIT;
pub use runtime::MAX_WEBHOOK_EVENT_LIST_LIMIT;
pub use runtime::MachineEndpointUpsertParams;
pub use runtime::MachineRegistryListPage;
pub use runtime::MachineRegistryListParams;
pub use runtime::MachineRegistryStore;
pub use runtime::MachineRegistryUpsertParams;
pub use runtime::MailboxAckParams;
pub use runtime::MailboxClaim;
pub use runtime::MailboxClaimParams;
pub use runtime::MailboxDispatchClaimParams;
pub use runtime::MailboxEnqueueOutcome;
pub use runtime::MailboxEnqueueParams;
pub use runtime::MailboxFailDisposition;
pub use runtime::MailboxFailParams;
pub use runtime::MailboxMessagePage;
pub use runtime::MailboxMessageStore;
pub use runtime::MailboxMessageStoreListParams;
pub use runtime::ManagedWorktreeAssignmentTarget;
pub use runtime::ManagedWorktreeAttachParams;
pub use runtime::ManagedWorktreeCleanupFailureParams;
pub use runtime::ManagedWorktreeCreateParams;
pub use runtime::ManagedWorktreeDetachParams;
pub use runtime::ManagedWorktreeListPage;
pub use runtime::ManagedWorktreeMergeCandidateRecordParams;
pub use runtime::ManagedWorktreeReleaseParams;
pub use runtime::ManagedWorktreeStatusUpdateParams;
pub use runtime::ManagedWorktreeStore;
pub use runtime::MemoryStore;
pub use runtime::MonitorStore;
pub use runtime::PendingInteractionListParams;
pub use runtime::PendingInteractionPage;
pub use runtime::PendingInteractionRespondForSourceParams;
pub use runtime::RemoteControlEnrollmentRecord;
pub use runtime::RuntimeDbPath;
pub use runtime::ScheduleStore;
pub use runtime::ThreadFilterOptions;
pub use runtime::ThreadGoalPlanAddOutcome;
pub use runtime::ThreadGoalPlanAddParams;
pub use runtime::ThreadGoalPlanAdvanceOutcome;
pub use runtime::ThreadGoalPlanAppendParams;
pub use runtime::ThreadGoalPlanCreateParams;
pub use runtime::ThreadGoalPlanListPage;
pub use runtime::ThreadGoalPlanNodeCreateParams;
pub use runtime::ThreadMonitorCreateParams;
pub use runtime::ThreadMonitorEventCreateParams;
pub use runtime::ThreadMonitorUpdate;
pub use runtime::ThreadScheduleClaim;
pub use runtime::ThreadScheduleCreateParams;
pub use runtime::ThreadScheduleDueClaimParams;
pub use runtime::ThreadScheduleNowClaimParams;
pub use runtime::ThreadScheduleUpdate;
pub use runtime::WEBHOOK_EVENT_DEDUPE_CONFLICT_MESSAGE;
pub use runtime::WORKFLOW_STEP_APPROVAL_APPROVED;
pub use runtime::WORKFLOW_STEP_APPROVAL_PENDING;
pub use runtime::WORKFLOW_STEP_APPROVAL_REJECTED;
pub use runtime::WebhookEventIngestOutcome;
pub use runtime::WebhookEventIngestParams;
pub use runtime::WebhookEventListPage;
pub use runtime::WebhookEventListParams;
pub use runtime::WebhookEventStore;
pub use runtime::WorkflowGoalPlanProjectionOutcome;
pub use runtime::WorkflowGoalPlanProjectionParams;
pub use runtime::WorkflowMonitorObservationOutcome;
pub use runtime::WorkflowMonitorObservationParams;
pub use runtime::WorkflowRunAdvanceOutcome;
pub use runtime::WorkflowRunAdvanceParams;
pub use runtime::WorkflowRunBranchAdmission;
pub use runtime::WorkflowRunBranchAdmissionOutcome;
pub use runtime::WorkflowRunBranchAdmissionParams;
pub use runtime::WorkflowRunBranchReconcileOutcome;
pub use runtime::WorkflowRunBranchReconcileParams;
pub use runtime::WorkflowRunCancelParams;
pub use runtime::WorkflowRunClaimOutcome;
pub use runtime::WorkflowRunClaimParams;
pub use runtime::WorkflowRunCreateParams;
pub use runtime::WorkflowRunListPage;
pub use runtime::WorkflowRunPauseParams;
pub use runtime::WorkflowRunResumeParams;
pub use runtime::WorkflowRunStatusMutationOutcome;
pub use runtime::WorkflowRunStepApprovalDecision;
pub use runtime::WorkflowRunStepApprovalOutcome;
pub use runtime::WorkflowRunStepApprovalParams;
pub use runtime::WorkflowRunVerifierClaimOutcome;
pub use runtime::WorkflowRunVerifierClaimParams;
pub use runtime::WorkflowRunVerifierClaimSelection;
pub use runtime::WorkflowRunVerifierOutcomeStatus;
pub use runtime::WorkflowRunVerifierRecordResultOutcome;
pub use runtime::WorkflowRunVerifierRecordResultParams;
pub use runtime::WorkflowRunVerifierResultSummary;
pub use runtime::WorkflowSpecCreateParams;
pub use runtime::WorkflowSpecListPage;
pub use runtime::WorkflowStore;
pub use runtime::WorkflowTimerClaim;
pub use runtime::WorkflowTimerClaimParams;
pub use runtime::WorkflowTimerFireCompleteOutcome;
pub use runtime::WorkflowTimerFireCompleteParams;
pub use runtime::goals_db_filename;
pub use runtime::goals_db_path;
pub use runtime::logs_db_filename;
pub use runtime::logs_db_path;
pub use runtime::memories_db_filename;
pub use runtime::memories_db_path;
pub use runtime::runtime_db_paths;
pub use runtime::sqlite_integrity_check;
pub use runtime::state_db_filename;
pub use runtime::state_db_path;
pub use telemetry::DbTelemetry;
pub use telemetry::DbTelemetryHandle;
pub use telemetry::install_process_db_telemetry;
pub use telemetry::record_backfill_gate;
pub use telemetry::record_fallback;

/// Environment variable for overriding the SQLite state database home directory.
pub const SQLITE_HOME_ENV: &str = "CODEX_SQLITE_HOME";

pub const LOGS_DB_FILENAME: &str = "logs_2.sqlite";
pub const GOALS_DB_FILENAME: &str = "goals_1.sqlite";
pub const MEMORIES_DB_FILENAME: &str = "memories_1.sqlite";
pub const STATE_DB_FILENAME: &str = "state_5.sqlite";

/// Errors encountered during DB operations. Tags: [stage]
pub const DB_ERROR_METRIC: &str = "codex.db.error";
/// Metrics on backfill process. Tags: [status]
pub const DB_METRIC_BACKFILL: &str = "codex.db.backfill";
/// Metrics on backfill duration. Tags: [status]
pub const DB_METRIC_BACKFILL_DURATION_MS: &str = "codex.db.backfill.duration_ms";
/// SQLite initialization attempts. Tags: [status, phase, db, error]
pub const DB_INIT_METRIC: &str = "codex.sqlite.init.count";
/// SQLite initialization latency. Tags: [status, phase, db, error]
pub const DB_INIT_DURATION_METRIC: &str = "codex.sqlite.init.duration_ms";
/// Rollout fallback attempts. Tags: [caller, reason]
pub const DB_FALLBACK_METRIC: &str = "codex.sqlite.fallback.count";
